/**:
  ros__parameters:
    camera:
      # 相機內部參數矩陣
      matrix: [
        924.07073975, 0.0, 643.87634277,
        0.0, 921.46142578, 346.78930664,
        0.0, 0.0, 1.0
      ]

      # 畸變係數
      distortion: [
        0.0,
        0.0,
        0.0,
        0.0,
        0.0
      ]

      # 手眼校正旋轉矩陣
    hand_eye:
      rotation: [
          1., 0., 0.,
          0., 1., 0.,
          0., 0., 1.
        ]

        # 手眼校正平移向量(單位:m)
      translation: [
          0.034056536902726448,
          -0.061831443624643156,
          -0.11779090512261667
        ]
